-- 120 questions (12 per category), seeded with version 1. Every question
-- carries exactly four written answer choices worth 0/1/2/3 on the same
-- ladder: nothing in place / ad hoc / documented / documented and running
-- well. is_quick_scan flags the 2 per category used by the free Quick
-- Scan; the Full Assessment uses all 12. See modules/assessments for the
-- scoring engine that consumes this.

-- Operations (12 questions, 2 quick-scan)
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Operations'), 'Do you have written, step-by-step instructions for how your core day-to-day work gets done?', 'multiple_choice', '[{"value":0,"label":"No — it''s all in people''s heads."},{"value":1,"label":"Some of it''s written down, but most of it isn''t."},{"value":2,"label":"Yes, we have documented instructions."},{"value":3,"label":"Yes, documented and the team actually follows them."}]'::jsonb, 1, true, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Operations'), 'If you disappeared for two weeks, would your team know exactly what to do without calling you?', 'multiple_choice', '[{"value":0,"label":"No — things would stall pretty fast."},{"value":1,"label":"They''d muddle through, but a lot would rely on guessing."},{"value":2,"label":"Mostly — there''s enough documented for them to keep going."},{"value":3,"label":"Yes, without missing a beat."}]'::jsonb, 2, true, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Operations'), 'Do you have a documented process for onboarding a new customer or client?', 'multiple_choice', '[{"value":0,"label":"No, we figure it out each time."},{"value":1,"label":"There''s a rough routine, but it''s not written down."},{"value":2,"label":"Yes, we have a documented onboarding process."},{"value":3,"label":"Yes, documented and every customer gets the same experience."}]'::jsonb, 3, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Operations'), 'Is there a clear, written process for how a job or order moves from "started" to "delivered"?', 'multiple_choice', '[{"value":0,"label":"No, it just happens however it happens."},{"value":1,"label":"There''s an informal flow, but nothing written."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and the team follows it start to finish."}]'::jsonb, 4, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Operations'), 'Do you track how long your key processes take, or would you have to guess?', 'multiple_choice', '[{"value":0,"label":"We''d have to guess."},{"value":1,"label":"We have a rough sense, but nothing tracked."},{"value":2,"label":"Yes, we track it."},{"value":3,"label":"Yes, we track it and use it to improve."}]'::jsonb, 5, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Operations'), 'Is there a written process for handling a customer complaint or a mistake?', 'multiple_choice', '[{"value":0,"label":"No, whoever''s around handles it their own way."},{"value":1,"label":"There''s an unwritten approach people generally follow."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and consistently used."}]'::jsonb, 6, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Operations'), 'Is there a defined process for ordering inventory or supplies, or does someone just "handle it"?', 'multiple_choice', '[{"value":0,"label":"Someone just handles it, no process."},{"value":1,"label":"There''s a habit, but it''s not written down."},{"value":2,"label":"Yes, there''s a documented process."},{"value":3,"label":"Yes, documented and it runs smoothly."}]'::jsonb, 7, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Operations'), 'If a key piece of equipment or software broke tomorrow, is there a documented backup plan?', 'multiple_choice', '[{"value":0,"label":"No plan — we''d scramble."},{"value":1,"label":"We''d figure something out, but nothing''s written down."},{"value":2,"label":"Yes, there''s a documented backup plan."},{"value":3,"label":"Yes, documented and we''ve actually tested it."}]'::jsonb, 8, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Operations'), 'Do you have a checklist or process for quality control before something goes out the door?', 'multiple_choice', '[{"value":0,"label":"No, there''s no check."},{"value":1,"label":"Someone eyeballs it, but it''s not formal."},{"value":2,"label":"Yes, we have a documented checklist."},{"value":3,"label":"Yes, documented and used every time."}]'::jsonb, 9, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Operations'), 'Is there a documented process for how you open and close each day or location?', 'multiple_choice', '[{"value":0,"label":"No, whoever''s there does their own thing."},{"value":1,"label":"There''s a habit, but nothing written."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and followed every day."}]'::jsonb, 10, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Operations'), 'Do you have a written process for handling returns, refunds, or cancellations?', 'multiple_choice', '[{"value":0,"label":"No, it''s decided case by case with no guide."},{"value":1,"label":"There''s an unwritten rule of thumb."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and applied consistently."}]'::jsonb, 11, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Operations'), 'Is there a clear, documented escalation process when something goes wrong operationally?', 'multiple_choice', '[{"value":0,"label":"No, people just figure out who to tell."},{"value":1,"label":"There''s an informal chain people generally use."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and everyone knows it."}]'::jsonb, 12, false, 1, true);

-- Systems (12 questions, 2 quick-scan)
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Systems'), 'Do you use one central system to track your customers, or is it scattered across notebooks, spreadsheets, and memory?', 'multiple_choice', '[{"value":0,"label":"Scattered — there''s no central system."},{"value":1,"label":"Mostly a spreadsheet or notebook, nothing formal."},{"value":2,"label":"Yes, we use one documented system."},{"value":3,"label":"Yes, one system, and the whole team actually uses it."}]'::jsonb, 1, true, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Systems'), 'Do you have a system that tracks the status of every open job or order in one place?', 'multiple_choice', '[{"value":0,"label":"No, you''d have to ask around to find out."},{"value":1,"label":"Sort of — it lives in emails and texts, not one place."},{"value":2,"label":"Yes, there''s a documented system for it."},{"value":3,"label":"Yes, and it''s kept up to date in real time."}]'::jsonb, 2, true, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Systems'), 'Is your scheduling and calendaring handled through one shared system everyone can see?', 'multiple_choice', '[{"value":0,"label":"No, everyone keeps their own."},{"value":1,"label":"Partially — some of it''s shared, some isn''t."},{"value":2,"label":"Yes, it''s documented and shared."},{"value":3,"label":"Yes, shared and everyone actually keeps it current."}]'::jsonb, 3, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Systems'), 'Are your business records — contracts, invoices, files — stored in one organized system, or spread across emails and desktops?', 'multiple_choice', '[{"value":0,"label":"Spread across emails, drives, and desktops."},{"value":1,"label":"Mostly organized, but not consistently."},{"value":2,"label":"Yes, one documented, organized system."},{"value":3,"label":"Yes, organized and everyone knows where to find things."}]'::jsonb, 4, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Systems'), 'Do your different software tools talk to each other, or does someone manually re-enter the same data twice?', 'multiple_choice', '[{"value":0,"label":"Someone re-enters everything by hand."},{"value":1,"label":"A little bit connects, but a lot is manual."},{"value":2,"label":"Yes, the key tools are documented to connect."},{"value":3,"label":"Yes, connected and running smoothly with little manual work."}]'::jsonb, 5, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Systems'), 'Is there a system that alerts you automatically when something needs attention — low inventory, an overdue invoice, that kind of thing?', 'multiple_choice', '[{"value":0,"label":"No, someone has to notice and remember."},{"value":1,"label":"Sort of, but it depends on someone checking manually."},{"value":2,"label":"Yes, there''s a documented alert system."},{"value":3,"label":"Yes, documented and it actually catches things before they''re a problem."}]'::jsonb, 6, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Systems'), 'Do you have a documented process for how your business data gets backed up?', 'multiple_choice', '[{"value":0,"label":"No backup process at all."},{"value":1,"label":"Backups happen, but nobody wrote down how or when."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and regularly verified."}]'::jsonb, 7, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Systems'), 'Is there a single system of record for your financials, or do the numbers live in multiple places?', 'multiple_choice', '[{"value":0,"label":"Numbers live in a few different places."},{"value":1,"label":"Mostly one place, but not always kept current."},{"value":2,"label":"Yes, one documented system of record."},{"value":3,"label":"Yes, one system, current and trusted."}]'::jsonb, 8, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Systems'), 'Do you have a system for tracking employee time and attendance?', 'multiple_choice', '[{"value":0,"label":"No, it''s informal."},{"value":1,"label":"Somewhat, but it''s manual and inconsistent."},{"value":2,"label":"Yes, there''s a documented system."},{"value":3,"label":"Yes, documented and reliably used."}]'::jsonb, 9, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Systems'), 'Is there a documented system for managing passwords and access to your tools?', 'multiple_choice', '[{"value":0,"label":"No, everyone just has their own logins however they set them."},{"value":1,"label":"There''s a loose habit, nothing written down."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and actively maintained."}]'::jsonb, 10, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Systems'), 'Do you have a system for managing vendor or supplier information and contracts?', 'multiple_choice', '[{"value":0,"label":"No, that information is scattered or in someone''s head."},{"value":1,"label":"Somewhat organized, but not a real system."},{"value":2,"label":"Yes, there''s a documented system."},{"value":3,"label":"Yes, documented and kept current."}]'::jsonb, 11, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Systems'), 'Is there a system in place to track and report on the metrics that actually matter to the business?', 'multiple_choice', '[{"value":0,"label":"No, we don''t really track metrics."},{"value":1,"label":"We glance at a few numbers here and there."},{"value":2,"label":"Yes, there''s a documented reporting system."},{"value":3,"label":"Yes, documented and reviewed on a regular schedule."}]'::jsonb, 12, false, 1, true);

-- People (12 questions, 2 quick-scan)
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'People'), 'Does every role in your company have a written job description?', 'multiple_choice', '[{"value":0,"label":"No written job descriptions exist."},{"value":1,"label":"A few roles have something written, most don''t."},{"value":2,"label":"Yes, roles have documented job descriptions."},{"value":3,"label":"Yes, documented and actually used to guide the work."}]'::jsonb, 1, true, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'People'), 'Do you have a documented, repeatable hiring process?', 'multiple_choice', '[{"value":0,"label":"No, hiring happens however it happens."},{"value":1,"label":"There''s a rough routine, but nothing written down."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and consistently followed."}]'::jsonb, 2, true, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'People'), 'Is there a written onboarding plan for new hires, or do they just "shadow someone"?', 'multiple_choice', '[{"value":0,"label":"They just shadow someone, no plan."},{"value":1,"label":"There''s an informal routine people generally follow."},{"value":2,"label":"Yes, there''s a documented onboarding plan."},{"value":3,"label":"Yes, documented and every new hire gets it."}]'::jsonb, 3, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'People'), 'Do employees get regular, documented performance reviews?', 'multiple_choice', '[{"value":0,"label":"No reviews happen."},{"value":1,"label":"Feedback happens, but it''s informal and not written down."},{"value":2,"label":"Yes, there''s a documented review process."},{"value":3,"label":"Yes, documented and done on a reliable schedule."}]'::jsonb, 4, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'People'), 'Is there a written employee handbook or set of policies?', 'multiple_choice', '[{"value":0,"label":"No handbook exists."},{"value":1,"label":"A few policies exist informally, nothing compiled."},{"value":2,"label":"Yes, there''s a documented handbook."},{"value":3,"label":"Yes, documented and every employee actually has it."}]'::jsonb, 5, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'People'), 'Is there a documented process for how pay raises or bonuses get decided?', 'multiple_choice', '[{"value":0,"label":"No, it''s decided case by case with no real process."},{"value":1,"label":"There''s an unwritten sense of how it works."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and applied consistently."}]'::jsonb, 6, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'People'), 'Is there a clear org chart that shows who reports to whom?', 'multiple_choice', '[{"value":0,"label":"No org chart exists."},{"value":1,"label":"People generally know, but nothing''s written down."},{"value":2,"label":"Yes, there''s a documented org chart."},{"value":3,"label":"Yes, documented and kept up to date."}]'::jsonb, 7, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'People'), 'Do you have a documented plan for what happens if a key employee leaves tomorrow?', 'multiple_choice', '[{"value":0,"label":"No plan — it would be a scramble."},{"value":1,"label":"We''d figure it out, but nothing''s written down."},{"value":2,"label":"Yes, there''s a documented plan."},{"value":3,"label":"Yes, documented and we''re confident it would work."}]'::jsonb, 8, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'People'), 'Is there a formal training program for new skills, or is it all on-the-job trial and error?', 'multiple_choice', '[{"value":0,"label":"All trial and error, no program."},{"value":1,"label":"Some informal coaching happens, nothing structured."},{"value":2,"label":"Yes, there''s a documented training program."},{"value":3,"label":"Yes, documented and actively used."}]'::jsonb, 9, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'People'), 'Do you hold regular, structured team meetings with a set agenda?', 'multiple_choice', '[{"value":0,"label":"No regular meetings happen."},{"value":1,"label":"Meetings happen, but without a real agenda."},{"value":2,"label":"Yes, there''s a documented meeting structure."},{"value":3,"label":"Yes, documented and the meetings actually run well."}]'::jsonb, 10, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'People'), 'Is there a documented process for handling employee conflicts or performance issues?', 'multiple_choice', '[{"value":0,"label":"No, it''s handled however it comes up."},{"value":1,"label":"There''s an informal approach, nothing written down."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and consistently applied."}]'::jsonb, 11, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'People'), 'Do you have a written plan for how employees can grow or get promoted?', 'multiple_choice', '[{"value":0,"label":"No growth path exists."},{"value":1,"label":"It happens informally, case by case."},{"value":2,"label":"Yes, there''s a documented growth path."},{"value":3,"label":"Yes, documented and employees know what it takes."}]'::jsonb, 12, false, 1, true);

-- Leadership (12 questions, 2 quick-scan)
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Leadership'), 'Do you have a written vision or set of core values that actually guides decisions?', 'multiple_choice', '[{"value":0,"label":"No, nothing''s written down."},{"value":1,"label":"We have a rough sense of it, but it''s not written down."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and it genuinely shapes decisions."}]'::jsonb, 1, true, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Leadership'), 'Does your leadership team meet on a regular, scheduled cadence with a written agenda?', 'multiple_choice', '[{"value":0,"label":"No regular leadership meetings happen."},{"value":1,"label":"We meet occasionally, without a real agenda."},{"value":2,"label":"Yes, there''s a documented meeting cadence."},{"value":3,"label":"Yes, documented and those meetings actually drive decisions."}]'::jsonb, 2, true, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Leadership'), 'Is there a documented decision-making process for major business decisions?', 'multiple_choice', '[{"value":0,"label":"No, big decisions get made ad hoc."},{"value":1,"label":"There''s an unwritten sense of how it works."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and consistently followed."}]'::jsonb, 3, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Leadership'), 'Do you have written goals for the business that the whole team can see?', 'multiple_choice', '[{"value":0,"label":"No written goals exist."},{"value":1,"label":"Goals exist in leadership''s head, not shared."},{"value":2,"label":"Yes, there are documented goals."},{"value":3,"label":"Yes, documented, shared, and tracked."}]'::jsonb, 4, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Leadership'), 'Is there a clear, documented chain of command for who makes which decisions?', 'multiple_choice', '[{"value":0,"label":"No, it''s unclear who decides what."},{"value":1,"label":"People generally know, but nothing''s written down."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and it works well in practice."}]'::jsonb, 5, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Leadership'), 'Do you hold yourself and your leadership team accountable with any kind of written scorecard?', 'multiple_choice', '[{"value":0,"label":"No scorecard exists."},{"value":1,"label":"We have a rough sense of how things are going, nothing written."},{"value":2,"label":"Yes, there''s a documented scorecard."},{"value":3,"label":"Yes, documented and reviewed regularly."}]'::jsonb, 6, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Leadership'), 'Is there a documented succession plan if you stepped away from the business?', 'multiple_choice', '[{"value":0,"label":"No plan exists."},{"value":1,"label":"We''ve talked about it, but nothing''s written down."},{"value":2,"label":"Yes, there''s a documented plan."},{"value":3,"label":"Yes, documented and the right people know it."}]'::jsonb, 7, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Leadership'), 'Do you have a formal process for communicating company updates to the whole team?', 'multiple_choice', '[{"value":0,"label":"No formal process — updates trickle out however."},{"value":1,"label":"There''s a habit of sharing updates, nothing structured."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and updates reliably reach everyone."}]'::jsonb, 8, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Leadership'), 'Is there a written plan for how the company handles a crisis or major setback?', 'multiple_choice', '[{"value":0,"label":"No plan exists."},{"value":1,"label":"We''d figure it out in the moment."},{"value":2,"label":"Yes, there''s a documented plan."},{"value":3,"label":"Yes, documented and the team knows their role in it."}]'::jsonb, 9, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Leadership'), 'Do you document lessons learned after major projects or decisions?', 'multiple_choice', '[{"value":0,"label":"No, we just move on to the next thing."},{"value":1,"label":"We talk about it informally, nothing''s written down."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and it actually changes how we operate."}]'::jsonb, 10, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Leadership'), 'Is there a defined process for how new ideas or initiatives get approved and prioritized?', 'multiple_choice', '[{"value":0,"label":"No process — whoever''s loudest wins."},{"value":1,"label":"There''s an informal sense of how it works."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and consistently used."}]'::jsonb, 11, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Leadership'), 'Do you have a documented process for evaluating your own leadership team''s performance?', 'multiple_choice', '[{"value":0,"label":"No, leadership doesn''t get evaluated formally."},{"value":1,"label":"It happens informally, nothing written down."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and taken seriously."}]'::jsonb, 12, false, 1, true);

-- Sales (12 questions, 2 quick-scan)
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Sales'), 'Do you have a documented, repeatable sales process from first contact to close?', 'multiple_choice', '[{"value":0,"label":"No, every salesperson does it their own way."},{"value":1,"label":"There''s a rough approach, but nothing''s written down."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and the team actually follows it."}]'::jsonb, 1, true, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Sales'), 'Do you track your leads and their status in one place, or does it live in someone''s head?', 'multiple_choice', '[{"value":0,"label":"It lives in someone''s head."},{"value":1,"label":"Partially tracked, but inconsistently."},{"value":2,"label":"Yes, it''s tracked in a documented system."},{"value":3,"label":"Yes, tracked consistently and reviewed regularly."}]'::jsonb, 2, true, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Sales'), 'Is there a written script or talk track your team uses for sales conversations?', 'multiple_choice', '[{"value":0,"label":"No, everyone winds it themselves."},{"value":1,"label":"There''s a rough sense of what to say, nothing written."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and the team actually uses it."}]'::jsonb, 3, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Sales'), 'Is there a documented process for following up with a lead that doesn''t respond right away?', 'multiple_choice', '[{"value":0,"label":"No, if they don''t respond it''s dropped."},{"value":1,"label":"Follow-up happens sometimes, inconsistently."},{"value":2,"label":"Yes, there''s a documented follow-up process."},{"value":3,"label":"Yes, documented and consistently worked."}]'::jsonb, 4, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Sales'), 'Do you have written, standard pricing, or is every deal negotiated from scratch?', 'multiple_choice', '[{"value":0,"label":"Every deal is negotiated from scratch."},{"value":1,"label":"There''s a rough sense of pricing, nothing written down."},{"value":2,"label":"Yes, pricing is documented."},{"value":3,"label":"Yes, documented and consistently held to."}]'::jsonb, 5, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Sales'), 'Is there a documented process for creating and sending proposals or quotes?', 'multiple_choice', '[{"value":0,"label":"No, each one is built from scratch."},{"value":1,"label":"There''s a rough template someone reuses informally."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and quick to produce."}]'::jsonb, 6, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Sales'), 'Do you track conversion rates at each stage of your sales process?', 'multiple_choice', '[{"value":0,"label":"No, we don''t track that."},{"value":1,"label":"We have a rough sense, but nothing tracked."},{"value":2,"label":"Yes, it''s tracked."},{"value":3,"label":"Yes, tracked and reviewed regularly."}]'::jsonb, 7, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Sales'), 'Is there a defined process for handing off a new sale to fulfillment or delivery?', 'multiple_choice', '[{"value":0,"label":"No, it''s whatever the salesperson happens to communicate."},{"value":1,"label":"There''s a rough habit, nothing written down."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and nothing falls through the cracks."}]'::jsonb, 8, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Sales'), 'Do you have a documented referral or repeat-business process?', 'multiple_choice', '[{"value":0,"label":"No, referrals just happen or they don''t."},{"value":1,"label":"We ask sometimes, informally."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and it''s a real source of business."}]'::jsonb, 9, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Sales'), 'Is there a written process for what happens when a deal is lost?', 'multiple_choice', '[{"value":0,"label":"No, it''s just written off."},{"value":1,"label":"Someone might note it, informally."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and the reasons get reviewed."}]'::jsonb, 10, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Sales'), 'Do you have sales targets that are written down and tracked regularly?', 'multiple_choice', '[{"value":0,"label":"No targets exist."},{"value":1,"label":"There''s a rough number in mind, not tracked."},{"value":2,"label":"Yes, targets are documented."},{"value":3,"label":"Yes, documented and tracked regularly."}]'::jsonb, 11, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Sales'), 'Is there a documented onboarding process for training a new salesperson?', 'multiple_choice', '[{"value":0,"label":"No, they just shadow someone."},{"value":1,"label":"There''s an informal routine, nothing written down."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and new hires ramp up quickly."}]'::jsonb, 12, false, 1, true);

-- Marketing (12 questions, 2 quick-scan)
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Marketing'), 'Do you have a written marketing plan, or does marketing happen whenever there''s time?', 'multiple_choice', '[{"value":0,"label":"It happens whenever there''s time, no plan."},{"value":1,"label":"There''s a rough sense of what to do, nothing written."},{"value":2,"label":"Yes, there''s a documented plan."},{"value":3,"label":"Yes, documented and consistently executed."}]'::jsonb, 1, true, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Marketing'), 'Do you track which marketing efforts actually produce customers?', 'multiple_choice', '[{"value":0,"label":"No, we don''t track that."},{"value":1,"label":"We have a rough sense, but nothing tracked."},{"value":2,"label":"Yes, it''s tracked."},{"value":3,"label":"Yes, tracked and it shapes where we spend."}]'::jsonb, 2, true, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Marketing'), 'Is there a documented, consistent brand — logo, colors, messaging — used everywhere?', 'multiple_choice', '[{"value":0,"label":"No, it varies from one place to the next."},{"value":1,"label":"Mostly consistent, but nothing written down as a standard."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and consistently applied everywhere."}]'::jsonb, 3, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Marketing'), 'Do you have a content or posting calendar that''s actually followed?', 'multiple_choice', '[{"value":0,"label":"No calendar, posting happens whenever."},{"value":1,"label":"There''s a loose plan, not really followed."},{"value":2,"label":"Yes, there''s a documented calendar."},{"value":3,"label":"Yes, documented and consistently followed."}]'::jsonb, 4, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Marketing'), 'Is there a documented process for how leads get generated?', 'multiple_choice', '[{"value":0,"label":"No, leads just show up however they show up."},{"value":1,"label":"There''s a rough sense of where leads come from."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and deliberately run."}]'::jsonb, 5, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Marketing'), 'Is there a written process for responding to reviews or managing online reputation?', 'multiple_choice', '[{"value":0,"label":"No process, reviews get handled whenever someone notices."},{"value":1,"label":"There''s a habit of responding, nothing written down."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and consistently followed."}]'::jsonb, 6, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Marketing'), 'Do you have a documented email or follow-up sequence for leads who aren''t ready to buy yet?', 'multiple_choice', '[{"value":0,"label":"No, those leads just go cold."},{"value":1,"label":"Someone follows up occasionally, informally."},{"value":2,"label":"Yes, there''s a documented sequence."},{"value":3,"label":"Yes, documented and running automatically."}]'::jsonb, 7, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Marketing'), 'Is your website''s content and messaging kept up to date on a regular schedule?', 'multiple_choice', '[{"value":0,"label":"No, it hasn''t been touched in a long time."},{"value":1,"label":"It gets updated occasionally, whenever someone remembers."},{"value":2,"label":"Yes, there''s a documented update schedule."},{"value":3,"label":"Yes, documented and kept genuinely current."}]'::jsonb, 8, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Marketing'), 'Do you have a documented process for gathering and using customer testimonials?', 'multiple_choice', '[{"value":0,"label":"No, testimonials just happen to come in sometimes."},{"value":1,"label":"We ask occasionally, informally."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and actively used in marketing."}]'::jsonb, 9, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Marketing'), 'Is there a defined target customer or ideal client profile written down anywhere?', 'multiple_choice', '[{"value":0,"label":"No, we take whoever comes."},{"value":1,"label":"We have a rough sense in our heads, nothing written."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and it shapes our marketing."}]'::jsonb, 10, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Marketing'), 'If you run paid advertising, is there a documented budget and plan behind it?', 'multiple_choice', '[{"value":0,"label":"No plan, spending is reactive."},{"value":1,"label":"There''s a rough sense of budget, nothing written down."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and managed deliberately."}]'::jsonb, 11, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Marketing'), 'Is there a process for measuring return on your marketing spend?', 'multiple_choice', '[{"value":0,"label":"No, we don''t measure it."},{"value":1,"label":"We have a rough sense, but nothing tracked."},{"value":2,"label":"Yes, it''s tracked."},{"value":3,"label":"Yes, tracked and it drives our decisions."}]'::jsonb, 12, false, 1, true);

-- Finance (12 questions, 2 quick-scan)
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Finance'), 'Do you review a profit and loss statement on a regular, scheduled basis?', 'multiple_choice', '[{"value":0,"label":"No, I rarely look at one."},{"value":1,"label":"I glance at it occasionally, no set schedule."},{"value":2,"label":"Yes, it''s a documented, scheduled review."},{"value":3,"label":"Yes, documented, scheduled, and it drives decisions."}]'::jsonb, 1, true, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Finance'), 'Do you know your exact profit margin on your core products or services?', 'multiple_choice', '[{"value":0,"label":"No, I''d be guessing."},{"value":1,"label":"I have a rough idea, not exact."},{"value":2,"label":"Yes, it''s documented and known."},{"value":3,"label":"Yes, documented, known, and tracked over time."}]'::jsonb, 2, true, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Finance'), 'Is there a documented process for invoicing customers promptly and consistently?', 'multiple_choice', '[{"value":0,"label":"No, invoicing happens whenever someone gets to it."},{"value":1,"label":"There''s a rough habit, nothing written down."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and consistently on time."}]'::jsonb, 3, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Finance'), 'Do you have a written budget you actually track spending against?', 'multiple_choice', '[{"value":0,"label":"No budget exists."},{"value":1,"label":"There''s a rough number in mind, not tracked."},{"value":2,"label":"Yes, there''s a documented budget."},{"value":3,"label":"Yes, documented and tracked regularly."}]'::jsonb, 4, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Finance'), 'Is there a documented process for collecting on overdue accounts?', 'multiple_choice', '[{"value":0,"label":"No, overdue accounts just linger."},{"value":1,"label":"Someone follows up occasionally, informally."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and consistently worked."}]'::jsonb, 5, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Finance'), 'Is there a documented process for approving expenses before they''re made?', 'multiple_choice', '[{"value":0,"label":"No, anyone spends as needed."},{"value":1,"label":"There''s an informal understanding, nothing written down."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and consistently followed."}]'::jsonb, 6, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Finance'), 'Do you have a cash flow forecast you look at regularly?', 'multiple_choice', '[{"value":0,"label":"No forecast exists."},{"value":1,"label":"I have a rough feel for it, nothing written down."},{"value":2,"label":"Yes, there''s a documented forecast."},{"value":3,"label":"Yes, documented and reviewed on a set schedule."}]'::jsonb, 7, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Finance'), 'Is there a clear, documented separation between business and personal finances?', 'multiple_choice', '[{"value":0,"label":"No, they''re mixed together."},{"value":1,"label":"Mostly separate, but not formally documented."},{"value":2,"label":"Yes, it''s documented and separated."},{"value":3,"label":"Yes, documented, separated, and consistently maintained."}]'::jsonb, 8, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Finance'), 'Do you have a documented payroll process that runs like clockwork?', 'multiple_choice', '[{"value":0,"label":"No, payroll is handled ad hoc."},{"value":1,"label":"It works, but nothing''s written down."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and runs smoothly every time."}]'::jsonb, 9, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Finance'), 'Is there a written process for how pricing decisions get made?', 'multiple_choice', '[{"value":0,"label":"No, pricing is decided on gut feel each time."},{"value":1,"label":"There''s a rough sense of it, nothing written down."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and consistently applied."}]'::jsonb, 10, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Finance'), 'Do you work with a bookkeeper or accountant on a regular, scheduled basis?', 'multiple_choice', '[{"value":0,"label":"No regular relationship exists."},{"value":1,"label":"Occasionally, but not on a set schedule."},{"value":2,"label":"Yes, there''s a documented, regular arrangement."},{"value":3,"label":"Yes, documented, regular, and genuinely useful to decisions."}]'::jsonb, 11, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Finance'), 'Is there a documented process for financial reporting to leadership or ownership?', 'multiple_choice', '[{"value":0,"label":"No formal reporting happens."},{"value":1,"label":"Numbers get shared informally sometimes."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and happens like clockwork."}]'::jsonb, 12, false, 1, true);

-- Technology (12 questions, 2 quick-scan)
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Technology'), 'Is there a documented inventory of every piece of software and technology the business relies on?', 'multiple_choice', '[{"value":0,"label":"No inventory exists."},{"value":1,"label":"There''s a rough sense of what we use, nothing written down."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and kept up to date."}]'::jsonb, 1, true, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Technology'), 'Is there a documented cybersecurity policy — passwords, phishing, data handling?', 'multiple_choice', '[{"value":0,"label":"No policy exists."},{"value":1,"label":"There''s an informal sense of best practice, nothing written down."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and the team actually follows it."}]'::jsonb, 2, true, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Technology'), 'Do you have a written process for turning on and shutting off an employee''s tech access?', 'multiple_choice', '[{"value":0,"label":"No process, it''s handled case by case."},{"value":1,"label":"There''s a rough habit, nothing written down."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and consistently followed."}]'::jsonb, 3, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Technology'), 'Do you have a written disaster recovery plan if your systems went down?', 'multiple_choice', '[{"value":0,"label":"No plan exists."},{"value":1,"label":"We''d figure it out, nothing''s written down."},{"value":2,"label":"Yes, there''s a documented plan."},{"value":3,"label":"Yes, documented and we''ve actually tested it."}]'::jsonb, 4, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Technology'), 'Is there a documented process for evaluating and approving new software purchases?', 'multiple_choice', '[{"value":0,"label":"No, anyone buys what they think they need."},{"value":1,"label":"There''s an informal check, nothing written down."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and consistently followed."}]'::jsonb, 5, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Technology'), 'Do you have a written policy for how company data can be accessed remotely?', 'multiple_choice', '[{"value":0,"label":"No policy exists."},{"value":1,"label":"There''s a loose understanding, nothing written down."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and enforced."}]'::jsonb, 6, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Technology'), 'Is there a documented process for keeping software and systems updated?', 'multiple_choice', '[{"value":0,"label":"No, updates happen whenever, if ever."},{"value":1,"label":"Someone updates things occasionally, informally."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and kept genuinely current."}]'::jsonb, 7, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Technology'), 'Do you have a clear plan for who handles IT issues when something breaks?', 'multiple_choice', '[{"value":0,"label":"No, whoever''s around tries to fix it."},{"value":1,"label":"There''s an informal go-to person, nothing written down."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and issues get resolved quickly."}]'::jsonb, 8, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Technology'), 'Is there a documented process for how customer data is protected?', 'multiple_choice', '[{"value":0,"label":"No process exists."},{"value":1,"label":"There''s a general sense of care, nothing written down."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and consistently followed."}]'::jsonb, 9, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Technology'), 'Do you have written guidelines for how AI or automation tools are used in the business?', 'multiple_choice', '[{"value":0,"label":"No guidelines exist."},{"value":1,"label":"People use them however they want, informally."},{"value":2,"label":"Yes, there are documented guidelines."},{"value":3,"label":"Yes, documented and consistently followed."}]'::jsonb, 10, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Technology'), 'Is there a documented technology budget reviewed on a regular basis?', 'multiple_choice', '[{"value":0,"label":"No budget exists."},{"value":1,"label":"There''s a rough sense of spending, nothing tracked."},{"value":2,"label":"Yes, there''s a documented budget."},{"value":3,"label":"Yes, documented and reviewed on a set schedule."}]'::jsonb, 11, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Technology'), 'Do you have a written plan for how technology supports the business as it grows?', 'multiple_choice', '[{"value":0,"label":"No plan exists."},{"value":1,"label":"We deal with it as problems come up."},{"value":2,"label":"Yes, there''s a documented plan."},{"value":3,"label":"Yes, documented and it''s actually guiding decisions."}]'::jsonb, 12, false, 1, true);

-- Vision (12 questions, 2 quick-scan)
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Vision'), 'Do you have a written three-to-five year vision for the business?', 'multiple_choice', '[{"value":0,"label":"No, it''s not written down anywhere."},{"value":1,"label":"I have a general idea, but it''s not written down."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and it actively guides decisions."}]'::jsonb, 1, true, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Vision'), 'Do you have a written plan for what the business looks like without you running it day to day?', 'multiple_choice', '[{"value":0,"label":"No plan exists."},{"value":1,"label":"I''ve thought about it, but it''s not written down."},{"value":2,"label":"Yes, there''s a documented plan."},{"value":3,"label":"Yes, documented and we''re actively working toward it."}]'::jsonb, 2, true, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Vision'), 'Is there a documented set of annual goals tied to that longer-term vision?', 'multiple_choice', '[{"value":0,"label":"No annual goals exist."},{"value":1,"label":"There''s a rough sense of goals, nothing written down."},{"value":2,"label":"Yes, they''re documented."},{"value":3,"label":"Yes, documented and tracked throughout the year."}]'::jsonb, 3, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Vision'), 'Is there a documented growth strategy — new markets, products, or locations?', 'multiple_choice', '[{"value":0,"label":"No strategy exists."},{"value":1,"label":"There''s a rough idea, nothing written down."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and being actively pursued."}]'::jsonb, 4, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Vision'), 'Do you have a written exit strategy or long-term ownership plan?', 'multiple_choice', '[{"value":0,"label":"No, I haven''t thought it through."},{"value":1,"label":"I''ve thought about it, but it''s not written down."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and periodically revisited."}]'::jsonb, 5, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Vision'), 'Is the company''s long-term vision communicated to the team in writing?', 'multiple_choice', '[{"value":0,"label":"No, the team doesn''t really hear about it."},{"value":1,"label":"It comes up in conversation sometimes, nothing written down."},{"value":2,"label":"Yes, it''s documented and shared."},{"value":3,"label":"Yes, documented, shared, and the team can repeat it back."}]'::jsonb, 6, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Vision'), 'Do you have a documented plan for how the business scales past its current size?', 'multiple_choice', '[{"value":0,"label":"No plan exists."},{"value":1,"label":"There''s a rough idea, nothing written down."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and actively being executed."}]'::jsonb, 7, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Vision'), 'Is there a written definition of what success actually looks like for the business?', 'multiple_choice', '[{"value":0,"label":"No, it''s never been defined."},{"value":1,"label":"I have a feel for it, but it''s not written down."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and used to measure progress."}]'::jsonb, 8, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Vision'), 'Do you revisit and update your written vision and goals on a regular schedule?', 'multiple_choice', '[{"value":0,"label":"No, they were never written down to begin with."},{"value":1,"label":"We revisit them occasionally, informally."},{"value":2,"label":"Yes, there''s a documented review schedule."},{"value":3,"label":"Yes, documented and consistently kept current."}]'::jsonb, 9, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Vision'), 'Is there a documented plan for major future investments — equipment, people, locations?', 'multiple_choice', '[{"value":0,"label":"No plan exists."},{"value":1,"label":"There''s a rough sense of what''s coming, nothing written down."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and budgeted for."}]'::jsonb, 10, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Vision'), 'Do you have a written competitive strategy — what makes you different and how you''ll stay that way?', 'multiple_choice', '[{"value":0,"label":"No, it''s never been written down."},{"value":1,"label":"I could explain it, but it''s not documented."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and it shapes real decisions."}]'::jsonb, 11, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Vision'), 'Is there a documented plan for how the business would be valued or sold one day, even if that''s far off?', 'multiple_choice', '[{"value":0,"label":"No, that''s never been considered."},{"value":1,"label":"I''ve thought about it, but nothing''s written down."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented and we manage the business with it in mind."}]'::jsonb, 12, false, 1, true);

-- Enterprise Readiness (12 questions, 2 quick-scan)
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Enterprise Readiness'), 'Could someone else step in and run this business tomorrow using what''s written down?', 'multiple_choice', '[{"value":0,"label":"No — it would fall apart without me."},{"value":1,"label":"Somewhat, but it would be rocky."},{"value":2,"label":"Mostly — there''s documentation to fall back on."},{"value":3,"label":"Yes, without missing a beat."}]'::jsonb, 1, true, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Enterprise Readiness'), 'Is the business''s value tied mostly to you personally, or to systems that run without you?', 'multiple_choice', '[{"value":0,"label":"Almost entirely tied to me personally."},{"value":1,"label":"Mostly tied to me, with a few things documented."},{"value":2,"label":"Fairly balanced — a good amount is documented and systemized."},{"value":3,"label":"Mostly tied to systems and documented processes, not to me."}]'::jsonb, 2, true, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Enterprise Readiness'), 'Is there a single, organized place where a buyer or investor could see how the business runs?', 'multiple_choice', '[{"value":0,"label":"No, that information doesn''t exist in one place."},{"value":1,"label":"Bits and pieces exist, but nothing organized."},{"value":2,"label":"Yes, there''s a documented, organized picture."},{"value":3,"label":"Yes, documented, organized, and genuinely ready to show."}]'::jsonb, 3, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Enterprise Readiness'), 'Do you have documented SOPs for the majority of your critical functions?', 'multiple_choice', '[{"value":0,"label":"No, very little is documented."},{"value":1,"label":"A handful of things are documented, not most."},{"value":2,"label":"Yes, most critical functions are documented."},{"value":3,"label":"Yes, documented and the team actually runs on them."}]'::jsonb, 4, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Enterprise Readiness'), 'Do you have clean, documented financials that would hold up to outside scrutiny?', 'multiple_choice', '[{"value":0,"label":"No, the financials are messy or incomplete."},{"value":1,"label":"Mostly there, but not organized for outside review."},{"value":2,"label":"Yes, they''re documented and clean."},{"value":3,"label":"Yes, documented, clean, and audit-ready."}]'::jsonb, 5, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Enterprise Readiness'), 'Is there a documented org structure that doesn''t depend entirely on the owner making every call?', 'multiple_choice', '[{"value":0,"label":"No, every decision runs through me."},{"value":1,"label":"A few things are delegated, nothing formal."},{"value":2,"label":"Yes, there''s a documented structure."},{"value":3,"label":"Yes, documented and the team genuinely operates within it."}]'::jsonb, 6, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Enterprise Readiness'), 'Do you have written contracts and agreements in place for key relationships — customers, vendors, employees?', 'multiple_choice', '[{"value":0,"label":"No, most relationships run on a handshake."},{"value":1,"label":"Some are in writing, most aren''t."},{"value":2,"label":"Yes, key relationships are documented."},{"value":3,"label":"Yes, documented and consistently kept current."}]'::jsonb, 7, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Enterprise Readiness'), 'Is there a documented plan for what happens to the business if you were unexpectedly unavailable for 90 days?', 'multiple_choice', '[{"value":0,"label":"No plan exists."},{"value":1,"label":"I''ve thought about it, but nothing''s written down."},{"value":2,"label":"Yes, there''s a documented plan."},{"value":3,"label":"Yes, documented and the right people know it."}]'::jsonb, 8, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Enterprise Readiness'), 'Do you have a system for tracking the metrics an outside buyer would actually want to see?', 'multiple_choice', '[{"value":0,"label":"No, we don''t track those metrics."},{"value":1,"label":"We have a rough sense, but nothing tracked properly."},{"value":2,"label":"Yes, it''s a documented system."},{"value":3,"label":"Yes, documented and those numbers are strong."}]'::jsonb, 9, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Enterprise Readiness'), 'Is your intellectual property — brand, processes, content — documented and protected?', 'multiple_choice', '[{"value":0,"label":"No, nothing''s been formally protected."},{"value":1,"label":"Some of it, informally, nothing systematic."},{"value":2,"label":"Yes, it''s documented and protected."},{"value":3,"label":"Yes, documented, protected, and actively maintained."}]'::jsonb, 10, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Enterprise Readiness'), 'Do you have a documented plan for reducing how much the business depends on you personally?', 'multiple_choice', '[{"value":0,"label":"No plan exists."},{"value":1,"label":"I''ve thought about it, but nothing''s written down."},{"value":2,"label":"Yes, there''s a documented plan."},{"value":3,"label":"Yes, documented and we''re actively executing it."}]'::jsonb, 11, false, 1, true);
insert into public.assessment_questions (category_id, question_text, answer_type, answer_options, sort_order, is_quick_scan, version, active) values
  ((select id from public.assessment_categories where name = 'Enterprise Readiness'), 'Is there a written record of the business''s systems, processes, and history that isn''t just in your head?', 'multiple_choice', '[{"value":0,"label":"No, it''s all in my head."},{"value":1,"label":"Bits of it are written down, most isn''t."},{"value":2,"label":"Yes, it''s documented."},{"value":3,"label":"Yes, documented, organized, and kept current."}]'::jsonb, 12, false, 1, true);

